{10: {'config': {'descripcion': 'Madrid',
                 'iconomapa': 'pin_cercanias',
                 'incidencias': 'http://infocer.renfe.es/informacionCercanias/incidenciasXML.do?login=aplinf1&password=HTULE593&idnucleo=10',
                 'lat': '40.40615564778484',
                 'lon': '-3.688957970842623',
                 'tarifas': 'http://www.renfe.com/viajeros/cercanias/madrid/abonos_y_descuentos/index.html'},
      'content': {'dateTimeUpdate': '20130101113000',
                  'estaciones': 'http://api.mo2o.com/apps/RenfeApp/contents/estaciones_10.xml.gz',
                  'lineas': 'http://api.mo2o.com/apps/RenfeApp/contents/lineas_10.xml.gz',
                  'mapaesquematico': 'http://api.mo2o.com/apps/RenfeApp/contents/mapaesquematico_10.xml.gz',
                  'mapaesquematicoimg': 'http://api.mo2o.com/apps/RenfeApp/redirect.php?file=esquematico_10.jpg.gz',
                  'name': 'MADRID',
                  'tarifas': 'http://api.mo2o.com/apps/RenfeApp/contents/matriz_10.xml.gz'}},
 20: {'config': {'descripcion': 'Asturias',
                 'iconomapa': 'pin_cercanias',
                 'incidencias': None,
                 'lat': '43.355864',
                 'lon': '-5.855475',
                 'tarifas': 'http://www.renfe.com/viajeros/cercanias/asturias/abonos_y_descuentos/index.html'},
      'content': {'dateTimeUpdate': '20120904131100',
                  'estaciones': 'http://api.mo2o.com/apps/RenfeApp/contents/estaciones_20.xml.gz',
                  'lineas': 'http://api.mo2o.com/apps/RenfeApp/contents/lineas_20.xml.gz',
                  'mapaesquematico': 'http://api.mo2o.com/apps/RenfeApp/contents/mapaesquematico_20.xml.gz',
                  'mapaesquematicoimg': 'http://api.mo2o.com/apps/RenfeApp/redirect.php?file=esquematico_20.jpg.gz',
                  'name': 'ASTURIAS',
                  'tarifas': 'http://api.mo2o.com/apps/RenfeApp/contents/matriz_20.xml.gz'}},
 30: {'config': {'descripcion': 'Sevilla',
                 'iconomapa': 'pin_cercanias',
                 'incidencias': None,
                 'lat': '37.39212777777778',
                 'lon': '-5.975269444444445',
                 'tarifas': 'http://www.renfe.com/viajeros/cercanias/sevilla/abonos_y_descuentos/index.html'},
      'content': {'dateTimeUpdate': '20130101113000',
                  'estaciones': 'http://api.mo2o.com/apps/RenfeApp/contents/estaciones_30.xml.gz',
                  'lineas': 'http://api.mo2o.com/apps/RenfeApp/contents/lineas_30.xml.gz',
                  'mapaesquematico': 'http://api.mo2o.com/apps/RenfeApp/contents/mapaesquematico_30.xml.gz',
                  'mapaesquematicoimg': 'http://api.mo2o.com/apps/RenfeApp/redirect.php?file=esquematico_30.jpg.gz',
                  'name': 'SEVILLA',
                  'tarifas': 'http://api.mo2o.com/apps/RenfeApp/contents/matriz_30.xml.gz'}},
 31: {'config': {'descripcion': u'C\xe1diz',
                 'iconomapa': 'pin_cercanias',
                 'incidencias': None,
                 'lat': '36.52900833333333',
                 'lon': '-6.288205555555557',
                 'tarifas': 'http://www.renfe.com/viajeros/cercanias/cadiz/abonos_y_descuentos/index.html'},
      'content': {'dateTimeUpdate': '20120904131100',
                  'estaciones': 'http://api.mo2o.com/apps/RenfeApp/contents/estaciones_31.xml.gz',
                  'lineas': 'http://api.mo2o.com/apps/RenfeApp/contents/lineas_31.xml.gz',
                  'mapaesquematico': 'http://api.mo2o.com/apps/RenfeApp/contents/mapaesquematico_31.xml.gz',
                  'mapaesquematicoimg': 'http://api.mo2o.com/apps/RenfeApp/redirect.php?file=esquematico_31.jpg.gz',
                  'name': 'CADIZ',
                  'tarifas': 'http://api.mo2o.com/apps/RenfeApp/contents/matriz_31.xml.gz'}},
 32: {'config': {'descripcion': u'M\xe1laga',
                 'iconomapa': 'pin_cercanias',
                 'incidencias': None,
                 'lat': '36.71804553239556',
                 'lon': '-4.416784240893862',
                 'tarifas': 'http://www.renfe.com/viajeros/cercanias/malaga/abonos_y_descuentos/index.html'},
      'content': {'dateTimeUpdate': '20120904131100',
                  'estaciones': 'http://api.mo2o.com/apps/RenfeApp/contents/estaciones_32.xml.gz',
                  'lineas': 'http://api.mo2o.com/apps/RenfeApp/contents/lineas_32.xml.gz',
                  'mapaesquematico': 'http://api.mo2o.com/apps/RenfeApp/contents/mapaesquematico_32.xml.gz',
                  'mapaesquematicoimg': 'http://api.mo2o.com/apps/RenfeApp/redirect.php?file=esquematico_32.jpg.gz',
                  'name': 'MALAGA',
                  'tarifas': 'http://api.mo2o.com/apps/RenfeApp/contents/matriz_32.xml.gz'}},
 40: {'config': {'descripcion': 'Valencia',
                 'iconomapa': 'pin_cercanias',
                 'incidencias': None,
                 'lat': '39.46693463866386',
                 'lon': '-0.3771842973461059',
                 'tarifas': 'http://www.renfe.com/viajeros/cercanias/valencia/abonos_y_descuentos/index.html'},
      'content': {'dateTimeUpdate': '20120904131100',
                  'estaciones': 'http://api.mo2o.com/apps/RenfeApp/contents/estaciones_40.xml.gz',
                  'lineas': 'http://api.mo2o.com/apps/RenfeApp/contents/lineas_40.xml.gz',
                  'mapaesquematico': 'http://api.mo2o.com/apps/RenfeApp/contents/mapaesquematico_40.xml.gz',
                  'mapaesquematicoimg': 'http://api.mo2o.com/apps/RenfeApp/redirect.php?file=esquematico_40.jpg.gz',
                  'name': 'VALENCIA',
                  'tarifas': 'http://api.mo2o.com/apps/RenfeApp/contents/matriz_40.xml.gz'}},
 41: {'config': {'descripcion': 'Murcia/Alicante',
                 'iconomapa': 'pin_cercanias',
                 'incidencias': None,
                 'lat': '37.97465',
                 'lon': '-1.129955555555556',
                 'tarifas': 'http://www.renfe.com/viajeros/cercanias/murciaalicante/abonos_y_descuentos/index.html'},
      'content': {'dateTimeUpdate': '20120904131100',
                  'estaciones': 'http://api.mo2o.com/apps/RenfeApp/contents/estaciones_41.xml.gz',
                  'lineas': 'http://api.mo2o.com/apps/RenfeApp/contents/lineas_41.xml.gz',
                  'mapaesquematico': 'http://api.mo2o.com/apps/RenfeApp/contents/mapaesquematico_41.xml.gz',
                  'mapaesquematicoimg': 'http://api.mo2o.com/apps/RenfeApp/redirect.php?file=esquematico_41.jpg.gz',
                  'name': 'MURCIA/ALICANTE',
                  'tarifas': 'http://api.mo2o.com/apps/RenfeApp/contents/matriz_41.xml.gz'}},
 50: {'config': {'descripcion': 'Barcelona',
                 'iconomapa': 'pin_rodalies',
                 'incidencias': 'http://infocer.renfe.es/informacionCercanias/incidenciasXML.do?login=aplinf4&password=PEPSI788&idnucleo=50',
                 'lat': '41.37922',
                 'lon': '2.140624',
                 'tarifas': 'http://www20.gencat.cat/portal/site/rodalies/menuitem.490b231a477c4d887fbe6affb0c0e1a0/?vgnextoid=a7cb559aeeeff210VgnVCM2000009b0c1e0aRCRD&vgnextchannel=a7cb559aeeeff210VgnVCM2000009b0c1e0aRCRD&vgnextfmt=default'},
      'content': {'dateTimeUpdate': '20120904131100',
                  'estaciones': 'http://api.mo2o.com/apps/RenfeApp/contents/estaciones_50.xml.gz',
                  'lineas': 'http://api.mo2o.com/apps/RenfeApp/contents/lineas_50.xml.gz',
                  'mapaesquematico': 'http://api.mo2o.com/apps/RenfeApp/contents/mapaesquematico_50.xml.gz',
                  'mapaesquematicoimg': 'http://api.mo2o.com/apps/RenfeApp/redirect.php?file=esquematico_50.jpg.gz',
                  'name': 'BARCELONA',
                  'tarifas': 'http://api.mo2o.com/apps/RenfeApp/contents/matriz_50.xml.gz'}},
 60: {'config': {'descripcion': 'Bilbao',
                 'iconomapa': 'pin_cercanias',
                 'incidencias': None,
                 'lat': '43.259609',
                 'lon': '-2.92915',
                 'tarifas': 'http://www.renfe.com/viajeros/cercanias/bilbao/abonos_y_descuentos/index.html'},
      'content': {'dateTimeUpdate': '20130308000100',
                  'estaciones': 'http://api.mo2o.com/apps/RenfeApp/contents/estaciones_60.xml.gz',
                  'lineas': 'http://api.mo2o.com/apps/RenfeApp/contents/lineas_60.xml.gz',
                  'mapaesquematico': 'http://api.mo2o.com/apps/RenfeApp/contents/mapaesquematico_60.xml.gz',
                  'mapaesquematicoimg': 'http://api.mo2o.com/apps/RenfeApp/redirect.php?file=esquematico_60.jpg.gz',
                  'name': 'BILBAO',
                  'tarifas': 'http://api.mo2o.com/apps/RenfeApp/contents/matriz_60.xml.gz'}},
 61: {'config': {'descripcion': u'San Sebasti\xe1n',
                 'iconomapa': 'pin_cercanias',
                 'incidencias': None,
                 'lat': '43.317669',
                 'lon': '-1.976704',
                 'tarifas': 'http://www.renfe.com/viajeros/cercanias/sansebastian/abonos_y_descuentos/index.html'},
      'content': {'dateTimeUpdate': '20120904131100',
                  'estaciones': 'http://api.mo2o.com/apps/RenfeApp/contents/estaciones_61.xml.gz',
                  'lineas': 'http://api.mo2o.com/apps/RenfeApp/contents/lineas_61.xml.gz',
                  'mapaesquematico': 'http://api.mo2o.com/apps/RenfeApp/contents/mapaesquematico_61.xml.gz',
                  'mapaesquematicoimg': 'http://api.mo2o.com/apps/RenfeApp/redirect.php?file=esquematico_61.jpg.gz',
                  'name': 'SAN SEBASTIAN',
                  'tarifas': 'http://api.mo2o.com/apps/RenfeApp/contents/matriz_61.xml.gz'}},
 62: {'config': {'descripcion': 'Santander',
                 'iconomapa': 'pin_cercanias',
                 'incidencias': None,
                 'lat': '43.458575',
                 'lon': '-3.811223',
                 'tarifas': 'http://www.renfe.com/viajeros/cercanias/santander/abonos_y_descuentos/index.html'},
      'content': {'dateTimeUpdate': '20120904131100',
                  'estaciones': 'http://api.mo2o.com/apps/RenfeApp/contents/estaciones_62.xml.gz',
                  'lineas': 'http://api.mo2o.com/apps/RenfeApp/contents/lineas_62.xml.gz',
                  'mapaesquematico': 'http://api.mo2o.com/apps/RenfeApp/contents/mapaesquematico_62.xml.gz',
                  'mapaesquematicoimg': 'http://api.mo2o.com/apps/RenfeApp/redirect.php?file=esquematico_62.jpg.gz',
                  'name': 'SANTANDER',
                  'tarifas': 'http://api.mo2o.com/apps/RenfeApp/contents/matriz_62.xml.gz'}},
 70: {'config': {'descripcion': 'Zaragoza',
                 'iconomapa': 'pin_cercanias',
                 'incidencias': None,
                 'lat': '41.658649',
                 'lon': '-0.911615',
                 'tarifas': 'http://www.renfe.com/viajeros/cercanias/zaragoza/abonos_y_descuentos/index.html'},
      'content': {'dateTimeUpdate': '20130101113000',
                  'estaciones': 'http://api.mo2o.com/apps/RenfeApp/contents/estaciones_70.xml.gz',
                  'lineas': 'http://api.mo2o.com/apps/RenfeApp/contents/lineas_70.xml.gz',
                  'mapaesquematico': 'http://api.mo2o.com/apps/RenfeApp/contents/mapaesquematico_70.xml.gz',
                  'mapaesquematicoimg': 'http://api.mo2o.com/apps/RenfeApp/redirect.php?file=esquematico_70.jpg.gz',
                  'name': 'ZARAGOZA',
                  'tarifas': 'http://api.mo2o.com/apps/RenfeApp/contents/matriz_70.xml.gz'}}}