CREATE TABLE ciudades (
  nucleo INTEGER NOT NULL,
  nombre  VARCHAR(30) NOT NULL,
  PRIMARY KEY (nucleo)
);

CREATE TABLE estaciones (
  id INTEGER NOT NULL,
  nucleo INTEGER NOT NULL,
  nombre VARCHAR(50) NOT NULL,
  FOREIGN KEY (nucleo) REFERENCES ciudad(nucleo),
  PRIMARY KEY (id)
);

INSERT INTO ciudades (nucleo, nombre) VALUES (20, "asturias");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (15205, 20, "AblaÃ±a");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (16403, 20, "Aviles");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (16006, 20, "Barros");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (15401, 20, "Calzada Asturias");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (15120, 20, "Campomanes");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (16302, 20, "Cancienes");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (16010, 20, "CiaÃ±o");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (15210, 20, "El Caleyo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (16011, 20, "El Entrego");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (16301, 20, "FerroÃ±es");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (15410, 20, "Gijon (Sanz Crespo)");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (15121, 20, "La Cobertoria");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (15217, 20, "La Corredoria");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (16008, 20, "La Felguera");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (15119, 20, "La Frecha");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (15206, 20, "La Pereda-Riosa");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (16402, 20, "La Rocica");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (15209, 20, "Las Segadas");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (15218, 20, "Llamaquique");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (16406, 20, "Los Campos");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (15300, 20, "Lugo de LLanera");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (15212, 20, "Lugones");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (15203, 20, "Mieres-Puente");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (15303, 20, "Monteana");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (16400, 20, "Nubledo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (15207, 20, "Olloniego");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (15211, 20, "Oviedo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (16005, 20, "PeÃ±a Rubia");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (15122, 20, "Pola de Lena");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (15118, 20, "Puente L.Fierros");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (16009, 20, "Sama");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (16405, 20, "San Juan de Nieva");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (16001, 20, "Santa Eulalia M.");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (15202, 20, "Santullano");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (15302, 20, "Serin");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (15208, 20, "Soto de Rey");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (16002, 20, "Tudela-Veguin");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (15200, 20, "Ujo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (15400, 20, "VeriÃ±a");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (15301, 20, "Villabona Astur");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (15305, 20, "Villabona-Tabladiell");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (16401, 20, "Villalegre");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (15123, 20, "Villallana");

INSERT INTO ciudades (nucleo, nombre) VALUES (50, "barcelona");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (72400, 50, "Aeroport");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79600, 50, "Arenys de Mar");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79404, 50, "Badalona");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (77106, 50, "BalenyÃ -Els Hostalets");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (77107, 50, "BalenyÃ -Tona-Seva");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (78705, 50, "BarberÃ  del VallÃ¨s");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (78804, 50, "Barcelona-Arc de Triomf");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79009, 50, "Barcelona-El Clot-AragÃ³");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79400, 50, "Barcelona-EstaciÃ³ de FranÃ§a");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (78806, 50, "Barcelona-La Sagrera-Meridiana");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (71802, 50, "Barcelona-Passeig de GrÃ cia");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (78805, 50, "Barcelona-PlaÃ§a de Catalunya");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (78802, 50, "Barcelona-Sant Andreu Arenal");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79004, 50, "Barcelona-Sant Andreu Comtal");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (71801, 50, "Barcelona-Sants");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (78801, 50, "Barcelona-Torre del BarÃ³");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (71708, 50, "Bellvitge");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79606, 50, "Blanes");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (77112, 50, "BorgonyÃ ");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79412, 50, "Cabrera de Mar-Vilassar de Mar");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (71601, 50, "Calafell");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79502, 50, "Caldes d'Estrac");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79603, 50, "Calella");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (77301, 50, "CampdevÃ nol");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79601, 50, "Canet de Mar");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79101, 50, "Cardedeu");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (78605, 50, "Castellbell i el Vilar-Monistrol de Mont");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (72210, 50, "Castellbisbal");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (71705, 50, "Castelldefels");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (77105, 50, "Centelles");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (78706, 50, "Cerdanyola del VallÃ¨s");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (72503, 50, "Cerdanyola-Universitat");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (72303, 50, "CornellÃ ");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (71604, 50, "Cubelles");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (71603, 50, "Cunit");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79407, 50, "El Masnou");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (72211, 50, "El Papiol");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (71707, 50, "El Prat de Llobregat");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (72201, 50, "El Vendrell");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (72203, 50, "Els Monjos");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (77103, 50, "FigarÃ³");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (71703, 50, "Garraf");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (71706, 50, "GavÃ ");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (72208, 50, "Gelida");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79100, 50, "Granollers Centre");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (77006, 50, "Granollers-Canovelles");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79105, 50, "Gualba");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79107, 50, "Hostalric");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (72202, 50, "L'ArboÃ§");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (72305, 50, "L'Hospitalet de Llobregat");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (77114, 50, "La Farga de BebiÃ©");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (77102, 50, "La Garriga");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (72205, 50, "La Granada");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79011, 50, "La Llagosta");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (77306, 50, "La Molina");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (77310, 50, "La Tor de Querol-Enveig");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (72206, 50, "Lavern-Subirats");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (77100, 50, "Les Franqueses del VallÃ¨s");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79109, 50, "Les Franqueses-Granollers Nord");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79102, 50, "Llinars del VallÃ¨s");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79200, 50, "MaÃ§anet-Massanes");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79605, 50, "Malgrat de Mar");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (77110, 50, "Manlleu");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (78600, 50, "Manresa");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (72209, 50, "Martorell");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79500, 50, "MatarÃ³");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (72300, 50, "Molins de Rei");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79006, 50, "Mollet-Sant Fost");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (77004, 50, "Mollet-Santa Rosa");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79005, 50, "Montcada i Reixac");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (78708, 50, "Montcada i Reixac-Manresa");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (78707, 50, "Montcada i Reixac-Santa Maria");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (78800, 50, "Montcada BifurcaciÃ³");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (77002, 50, "Montcada Ripollet");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79405, 50, "Montgat");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79406, 50, "Montgat Nord");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79007, 50, "MontmelÃ³");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79408, 50, "Ocata");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79103, 50, "Palautordera");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (77005, 50, "Parets del VallÃ¨s");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79604, 50, "Pineda de Mar");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (77304, 50, "Planoles");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (71704, 50, "Platja de Castelldefels");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79409, 50, "PremiÃ  de Mar");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (77309, 50, "PuigcerdÃ ");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (77303, 50, "Ribes de Freser");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79106, 50, "Riells i Viabrea-Breda");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (77200, 50, "Ripoll");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (72501, 50, "RubÃ­");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (78704, 50, "Sabadell Centre");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (78709, 50, "Sabadell Nord");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (78703, 50, "Sabadell Sud");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79403, 50, "Sant AdriÃ  del BesÃ²s");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79501, 50, "Sant Andreu de Llavaneres");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79104, 50, "Sant Celoni");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (72502, 50, "Sant Cugat del VallÃ¨s");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (72301, 50, "Sant Feliu de Llobregat");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (72302, 50, "Sant Joan DespÃ­");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (77104, 50, "Sant MartÃ­ de Centelles");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (78610, 50, "Sant Miquel de Gonteres-Viladecavalls");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79602, 50, "Sant Pol de Mar");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (77113, 50, "Sant Quirze de Besora");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (72207, 50, "Sant SadurnÃ­ d'Anoia");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (71600, 50, "Sant VicenÃ§ de Calders");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (78604, 50, "Sant VicenÃ§ de Castellet");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (77003, 50, "Santa PerpÃ¨tua de Mogoda");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79608, 50, "Santa Susanna");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (71602, 50, "Segur de Calafell");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (71701, 50, "Sitges");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (78700, 50, "Terrassa");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (78710, 50, "Terrassa Est");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79607, 50, "Tordera");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (77111, 50, "TorellÃ³");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (77305, 50, "Toses");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (77307, 50, "Urtx-Alp");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (78606, 50, "Vacarisses");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (78607, 50, "Vacarisses-Torreblanca");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (77109, 50, "Vic");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (71709, 50, "Viladecans");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (78609, 50, "Viladecavalls");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (72204, 50, "Vilafranca del PenedÃ¨s");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (71700, 50, "Vilanova i la GeltrÃº");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (79410, 50, "Vilassar de Mar");

INSERT INTO ciudades (nucleo, nombre) VALUES (60, "bilbao");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13200, 60, "Abando");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13118, 60, "Abaroa-San Miguel");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13206, 60, "Ametzola");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13101, 60, "Amurrio");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13121, 60, "Amurrio-Iparralde");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13117, 60, "Arakaldo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13108, 60, "Arbide");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13107, 60, "Areta");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13109, 60, "Arrankudiaga");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13111, 60, "Arrigorriaga");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13207, 60, "Autonomia");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13115, 60, "Bakiola");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13112, 60, "Basauri");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13113, 60, "Bidebieta-Basauri");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13400, 60, "Desertu-Barakaldo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13501, 60, "Galindo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13508, 60, "Gallarta");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13116, 60, "Inarratxu");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13402, 60, "La Iberia");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13119, 60, "La PeÃ±a");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13106, 60, "Llodio");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13103, 60, "Luiaondo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13305, 60, "Lutxana-Barakaldo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13120, 60, "Miribilla");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13506, 60, "Muskiz");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13303, 60, "Olabeaga");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13114, 60, "Ollargan");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13100, 60, "OrduÃ±a");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13504, 60, "Ortuella");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13404, 60, "PeÃ±ota");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13403, 60, "Portugalete");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13505, 60, "Putxeta");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13509, 60, "Sagrada Familia");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13102, 60, "Salbio");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13208, 60, "San Mames");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13104, 60, "Santa Cruz Llodio");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13405, 60, "Santurtzi");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13401, 60, "Sestao");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13502, 60, "Trapaga");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13110, 60, "Ugao-Miraballes");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13507, 60, "Urioste");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13503, 60, "Valle Trapaga-Trapaga");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13205, 60, "Zabalburu");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (13304, 60, "Zorrotza");

INSERT INTO ciudades (nucleo, nombre) VALUES (31, "cadiz");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51205, 31, "Aeropuerto de Jerez");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51406, 31, "Bahia Sur");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51405, 31, "Cadiz");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51407, 31, "Cortadura");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51400, 31, "El Puerto de Santa Maria");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51409, 31, "Estadio");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51300, 31, "Jerez de la Frontera");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51415, 31, "Las Aletas");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51401, 31, "Puerto Real");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51402, 31, "San Fernando");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51414, 31, "San Severiano");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51404, 31, "Segunda Aguada");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51416, 31, "Universidad");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51417, 31, "Valdelagrana");

INSERT INTO ciudades (nucleo, nombre) VALUES (10, "madrid");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (98305, 10, "Aeropuerto-T4");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (70103, 10, "Alcala de Henares");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (70107, 10, "Alcala de Henares-Universidad");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (19003, 10, "Alcobendas-S.Sebast. de los Reyes");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (35605, 10, "Alcorcon");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (12002, 10, "Alpedrete");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (35600, 10, "Aluche");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (60200, 10, "Aranjuez");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (10001, 10, "Aravaca");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (70002, 10, "Asamblea de Madrid-Entrevias");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (18000, 10, "Atocha");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (70105, 10, "Azuqueca");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (17009, 10, "Cantoblanco Universidad");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (12006, 10, "Cercedilla");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (17000, 10, "Chamartin");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (60105, 10, "Ciempozuelos");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (12004, 10, "Collado Mediano");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (17005, 10, "Colmenar Viejo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (70108, 10, "Coslada");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (12023, 10, "Cotos");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (35603, 10, "Cuatro Vientos");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (18004, 10, "Delicias");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (35702, 10, "Doce de Octubre");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (10010, 10, "El Barrial-C.Com.Pozuelo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (60109, 10, "El Casar");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (10203, 10, "El Escorial");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (17003, 10, "El Goloso");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (70003, 10, "El Pozo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (35609, 10, "Embajadores");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (35601, 10, "Fanjul");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (17001, 10, "Fuencarral");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (35002, 10, "Fuenlabrada");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (98003, 10, "Fuente de la Mora");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (10104, 10, "Galapagar-La Navata");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (37011, 10, "Getafe -Sector Tres");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (37002, 10, "Getafe Centro");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (60102, 10, "Getafe Industrial");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (70200, 10, "Guadalajara");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (35012, 10, "Humanes");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (70111, 10, "La Garena");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (35010, 10, "La Serna");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (35608, 10, "Laguna");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (35602, 10, "Las Aguilas");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (37010, 10, "Las Margaritas Universidad");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (10101, 10, "Las Matas");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (35610, 10, "Las Retamas");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (10005, 10, "Las Rozas");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (10202, 10, "Las Zorreras");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (35001, 10, "Leganes");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (12005, 10, "Los Molinos");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (12001, 10, "Los Negrales");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (10007, 10, "Majadahonda");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (70104, 10, "Meco");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (18003, 10, "Mendez Alvaro");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (35606, 10, "Mostoles");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (35607, 10, "Mostoles el Soto");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (18002, 10, "Nuevos Ministerios");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (35703, 10, "Orcasitas");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (37012, 10, "Parla");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (35011, 10, "Parque Polvoranca");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (10100, 10, "Pinar de las Rozas");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (60103, 10, "Pinto");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (18005, 10, "Piramides");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (97100, 10, "Pitis");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (10002, 10, "Pozuelo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (10000, 10, "Principe Pio");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (35704, 10, "Puente Alcocer");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (12020, 10, "Puerto de Navacerrada");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (97201, 10, "Ramon y Cajal");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (18001, 10, "Recoletos");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (10205, 10, "Robledo de Chavela");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (60107, 10, "San Cristobal de los Angeles");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (60101, 10, "San Cristobal Industrial");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (70101, 10, "San Fernando");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (35604, 10, "San Jose de Valderas");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (10201, 10, "San Yago");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (70109, 10, "Santa Eugenia");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (10206, 10, "Santa Maria de la Alameda");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (18101, 10, "Sol");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (70102, 10, "Torrejon de Ardoz");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (10103, 10, "Torrelodones");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (17004, 10, "Tres Cantos");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (19001, 10, "Universidad P.Comillas");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (19002, 10, "ValdelasFuentes");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (60104, 10, "Valdemoro");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (70001, 10, "Vallecas");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (70100, 10, "Vicalvaro");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (10200, 10, "Villalba");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (37001, 10, "Villaverde Alto");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (60100, 10, "Villaverde Bajo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (10204, 10, "Zarzalejo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (35009, 10, "Zarzaquemada");

INSERT INTO ciudades (nucleo, nombre) VALUES (32, "malaga");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (54505, 32, "Aeropuerto");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (54407, 32, "Aljaima");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (54405, 32, "Alora");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (54511, 32, "Benalmadena(A.Miel)");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (54410, 32, "Campanillas");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (54408, 32, "Cartama");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (54513, 32, "Carvajal");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (54510, 32, "El Pinillo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (54516, 32, "Fuengirola");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (54503, 32, "Guadalhorce");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (54508, 32, "La Colina");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (54518, 32, "Los Alamos");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (54515, 32, "Los Boliches");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (54412, 32, "Los Prados(Alora)");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (54413, 32, "MÃ¡laga-MarÃ­a Zambrano");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (54517, 32, "Malaga-Centro Alameda");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (54501, 32, "Malaga-Victoria Kent");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (54519, 32, "Montemar Alto");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (54406, 32, "Pizarra");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (54520, 32, "Plaza Mayor");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (54506, 32, "San Julian");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (54514, 32, "Torreblanca");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (54509, 32, "Torremolinos");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (54512, 32, "Torremuelle");

INSERT INTO ciudades (nucleo, nombre) VALUES (41, "murciaalicante");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (07004, 41, "Aguilas");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (07007, 41, "Aguilas el Labradorcico");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (62100, 41, "Albatera-Catral");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (06008, 41, "Alcantarilla-Los Romanos");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (06002, 41, "Alhama de Murcia");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (60911, 41, "Alicante/Alacant.T");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (06100, 41, "Almendricos");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (62001, 41, "Beniel");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (62003, 41, "Callosa de Segura");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (62101, 41, "Crevillente");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (62102, 41, "Elche Carrus/Elx Carrus");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (62103, 41, "Elche Parque/Elx Parc");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (62108, 41, "Elche-Mcias.");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (07003, 41, "Jaravia");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (06004, 41, "La Hoya");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (06001, 41, "Librilla");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (06005, 41, "Lorca San Diego");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (06006, 41, "Lorca-Sutullena");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (61200, 41, "Murcia del Carmen");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (61101, 41, "Murcia Mercancias");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (62002, 41, "Orihuela");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (06007, 41, "Puerto Lumbreras");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (07001, 41, "Pulpi");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (62109, 41, "Sant Gabriel");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (60913, 41, "Sant Vicent Centre, Apdro.");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (62104, 41, "Torrellano");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (06003, 41, "Totana");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (60914, 41, "Universidad de Alicante");

INSERT INTO ciudades (nucleo, nombre) VALUES (62, "santander");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14235, 62, "Arenas de IguÃ±a");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14206, 62, "Barcena");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14219, 62, "Boo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14218, 62, "Guarnizo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14203, 62, "Lantueno-Santiur.");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14211, 62, "Las Caldas de Be.");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14209, 62, "Las Fraguas");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14232, 62, "Lombera");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14210, 62, "Los Corrales Buelna");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14220, 62, "MaliaÃ±o");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14207, 62, "Molledo-Portolin");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14221, 62, "Muriedas");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14237, 62, "Muriedas-Bahia");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14231, 62, "Nueva MontaÃ±a");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14217, 62, "Parbayon");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14204, 62, "Pesquera");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14234, 62, "Pujayo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14202, 62, "Reinosa");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14216, 62, "Renedo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14233, 62, "Rio Ebro");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14208, 62, "Santa Cruz IguÃ±a");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14223, 62, "Santander");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14214, 62, "Sierrapando");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14213, 62, "Torrelavega");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14230, 62, "Valdecilla");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14212, 62, "Viernoles");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14236, 62, "VioÃ±o");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (14215, 62, "Zurita");

INSERT INTO ciudades (nucleo, nombre) VALUES (61, "sansebastian");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11409, 61, "Alegia de Oria");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11505, 61, "Andoain");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11504, 61, "Andoain-Centro");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11502, 61, "Anoeta");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11513, 61, "Ategorrieta");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11404, 61, "Beasain");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11503, 61, "Billabona-Zizurkil");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11305, 61, "Brincola");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11511, 61, "Donostia-San Sebastian");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11512, 61, "Gros");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11508, 61, "Hernani");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11507, 61, "Hernani-Centro");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11514, 61, "Herrera");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11408, 61, "Ikaztegieta");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11522, 61, "Intxaurrondo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11600, 61, "Irun");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11406, 61, "Itsasondo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11306, 61, "Legazpi");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11407, 61, "Legorreta");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11516, 61, "Lezo-Renteria");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11510, 61, "Loiola");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11509, 61, "Martutene");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11405, 61, "Ordizia");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11402, 61, "Ormaiztegui");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11515, 61, "Pasaia");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11500, 61, "Tolosa");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11501, 61, "Tolosa Centro");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11506, 61, "Urnieta");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11518, 61, "Ventas");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (11400, 61, "Zumarraga");

INSERT INTO ciudades (nucleo, nombre) VALUES (30, "sevilla");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (40121, 30, "Alcolea del Rio");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (40118, 30, "Arenillas");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51111, 30, "Bellavista");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (43005, 30, "Benacazon");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (50702, 30, "Brenes");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (43002, 30, "Camas");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51112, 30, "Cantaelgallo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (50701, 30, "Cantillana");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51050, 30, "Cartuja");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (40113, 30, "Cazalla-Constantina");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51104, 30, "Don Rodrigo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51103, 30, "Dos Hermanas");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (50704, 30, "El CaÃ±amo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51051, 30, "Estadio Olimpico");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (40114, 30, "Fabrica de Pedroso");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (50602, 30, "Guadajoz");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (50703, 30, "La Rinconada");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51101, 30, "La Salud");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51202, 30, "Las Cabezas de San Juan");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51203, 30, "Lebrija");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (50600, 30, "Lora del Rio");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (50700, 30, "Los Rosales");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51010, 30, "Padre Pio Palmete");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51009, 30, "Palacio de Congresos");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (40115, 30, "Pedroso");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (43027, 30, "Salteras");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51100, 30, "San Bernardo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (43000, 30, "San Jeronimo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (43004, 30, "Sanlucar la Mayor");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51003, 30, "Santa Justa");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (40122, 30, "Tocina");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51200, 30, "Utrera");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (43026, 30, "Valencina-Santiponce");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (43003, 30, "Villanueva del Ariscal y Olivares");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (40119, 30, "Villanueva del Rio y Minas");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (51110, 30, "Virgen del Rocio");

INSERT INTO ciudades (nucleo, nombre) VALUES (40, "valencia");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (65005, 40, "Albuixech");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (66211, 40, "Aldaia");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (64203, 40, "Alfafar - Benetusser");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (64105, 40, "AlgemesÂ¡");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (67216, 40, "Algimia");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (65209, 40, "Almassora");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (65202, 40, "Almenara");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (64104, 40, "Alzira");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (64107, 40, "Benifaio - Almussafes");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (66206, 40, "BuÃ±ol");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (65207, 40, "Burriana - Alquerias del NiÃ±o Perdido");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (64103, 40, "Carcaixent");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (65300, 40, "Castello de la Plana");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (64201, 40, "Catarroja");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (67211, 40, "Caudiel");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (66208, 40, "Cheste");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (66207, 40, "Chiva");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (66210, 40, "Circuit R. Tormo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (69104, 40, "Cullera");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (65007, 40, "El Puig");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (66203, 40, "El Rebollar");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (69101, 40, "El Romani");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (67221, 40, "Estivella - Albalat dels Tarongers");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (69110, 40, "Gandia");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (67223, 40, "Gilet");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (67212, 40, "Jerica - Viver");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (64006, 40, "L'Alcudia de Crespins");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (64007, 40, "L'Enova - Manuel");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (65203, 40, "La Llosa");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (64102, 40, "La Pobla Llarga");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (65201, 40, "Les Valls");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (66209, 40, "Loriguilla - Reva");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (65006, 40, "Massalfassar");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (64202, 40, "Massanassa");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (64003, 40, "Moixent");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (65205, 40, "Moncofa");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (64005, 40, "Montesa");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (67213, 40, "Navajas");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (65206, 40, "Nules - La Vilavella");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (69111, 40, "Platja i Grau de Gandia");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (65008, 40, "PuÃol");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (66202, 40, "Requena");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (65001, 40, "Roca - Cuper");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (65200, 40, "Sagunt");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (66201, 40, "San Antonio de Requena");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (67214, 40, "Segorbe - Arrabal");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (67215, 40, "Segorbe - Ciudad");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (66204, 40, "Siete Aguas");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (64200, 40, "Silla");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (69102, 40, "Sollana");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (67217, 40, "Soneja");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (69103, 40, "Sueca");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (69105, 40, "Tavernes de la Valldigna");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (66200, 40, "Utiel");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (65003, 40, "Valencia - Cabanyal");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (65002, 40, "Valencia - F.S.L.");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (66212, 40, "Valencia - Sant Isidre");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (65000, 40, "Valencia Nord");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (64004, 40, "Vallada");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (66205, 40, "Venta Mina");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (65208, 40, "Vila - Real");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (64100, 40, "Xativa");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (69107, 40, "Xeraco");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (65204, 40, "Xilxes");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (66214, 40, "Xirivella - Alqueries");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (69200, 40, "Xirivella - L'Alter");

INSERT INTO ciudades (nucleo, nombre) VALUES (70, "zaragoza");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (70800, 70, "Casetas");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (71100, 70, "Miraflores");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (70801, 70, "Utebo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (04040, 70, "Zaragoza Delicias");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (70806, 70, "Zaragoza Portillo");
INSERT INTO estaciones (id, nucleo, nombre) VALUES (70807, 70, "Zaragoza-Goya");

